"""Added all the tables from sqlalchemy models

Revision ID: 84912adf4ed2
Revises:
Create Date: 2022-02-06 17:52:44.444210

"""
import uuid

from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils import UUIDType

# revision identifiers, used by Alembic.
revision = '84912adf4ed2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_names',
                    sa.Column('id', UUIDType(binary=False), nullable=False, default=uuid.uuid4()),
                    sa.Column('stock_name', sa.String(), nullable=False, unique=True),
                    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('price_actions',
                    sa.Column('id', UUIDType(binary=False), nullable=False, default=uuid.uuid4()),
                    sa.Column('stock_id', UUIDType(binary=False), nullable=False),
                    sa.Column('hour_1_start', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.0'),
                              nullable=False),
                    sa.Column('hour_1_end', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.0'),
                              nullable=False),
                    sa.Column('hour_2_start', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.0'),
                              nullable=False),
                    sa.Column('hour_2_end', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.0'),
                              nullable=False),
                    sa.Column('hour_3_start', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.0'),
                              nullable=False),
                    sa.Column('hour_3_end', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.0'),
                              nullable=False),
                    sa.Column('hour_4_start', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.0'),
                              nullable=False),
                    sa.Column('hour_4_end', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.0'),
                              nullable=False),
                    sa.Column('hour_5_start', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.0'),
                              nullable=False),
                    sa.Column('hour_5_end', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.0'),
                              nullable=False),
                    sa.Column('hour_6_start', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.0'),
                              nullable=False),
                    sa.Column('hour_6_end', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.0'),
                              nullable=False),
                    sa.Column('hour_7_start', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.0'),
                              nullable=False),
                    sa.Column('hour_7_end', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.0'),
                              nullable=False),
                    sa.Column('price_date', sa.DATE(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(('stock_id',), ['stock_names.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('stock_id', 'price_date', name='_stock_price_date_uc')
                    )
    op.create_table('shortlisted_stocks',
                    sa.Column('id', UUIDType(binary=False), nullable=False, default=uuid.uuid4()),
                    sa.Column('stock_id', UUIDType(binary=False), nullable=False),
                    sa.Column('price_action_ids', sa.JSON(), nullable=False),
                    sa.Column('conditions_met_on', sa.DATE(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(('stock_id',), ['stock_names.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('stock_id', 'conditions_met_on', name='_shortlisted_date_uc')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shortlisted_stocks')
    op.drop_table('price_actions')
    op.drop_table('stock_names')
    # ### end Alembic commands ###
